### ISSUE TITLE
Node.js 14.15.0 missing from snap repository/store

### ISSUE THREAD

**Issue by richardlau** [nodejs/snap#1]
It looks like the most recent Node.js 14 available on the Snap store is 14.14.0:
![image](https://user-images.githubusercontent.com/5445507/98936688-332ea780-24dd-11eb-8068-11495b825072.png)

This repository contains the commit on the [`nodejs14` branch](https://github.com/nodejs/snap/tree/node14) to update to 14.15.0 (https://github.com/nodejs/snap/commit/25aa810160c2642acc675b62b82fe4ae13f6a6b2) but it doesn't appear to be in https://code.launchpad.net/~openjs/node-snap/+git/node-snap/+ref/node14 -- I guess the mirroring failed somehow?

**Comment by richardlau** [comment]
![image](https://user-images.githubusercontent.com/5445507/98937173-ec8d7d00-24dd-11eb-8943-e237953ee385.png)

**Comment by richardlau** [comment]
FWIW I did promote both 10.13.0 (which looks like it was picked up) and 14.15.0 (which has not been picked up) at the same time on 27 October 2020 -- Perhaps a race condition?

**Comment by richardlau** [comment]
https://github.com/nodejs/snap/runs/1316010589?check_suite_focus=true failed to push.

**Comment by rvagg** [comment]
a divergence in the repos, not sure how this happened, a race or maybe I messed up when I was setting this repo up:

launchpad:

```
commit 578484e6081fb5325d2f9afc7d84466ca39da9ab
Author: GitHub Actions <noreply@github.com>
Date:   Fri Oct 16 04:10:51 2020 +0000

    snap: (auto) updated to 14.14.0

commit 26e2bec08d528523d7bdc878df7b53aac0acf819
Author: GitHub Actions <noreply@github.com>
Date:   Thu Oct 15 12:11:37 2020 +0000

    snap: (auto) updated to 14.13.1
```

those two here:

```
commit e8bb6f1610fffbe59b1094c6b9e32bf4f9a0b851
Author: GitHub Actions <noreply@github.com>
Date:   Fri Oct 16 04:33:15 2020 +0000

    snap: (auto) updated to 14.14.0

commit 26e2bec08d528523d7bdc878df7b53aac0acf819
Author: GitHub Actions <noreply@github.com>
Date:   Thu Oct 15 12:11:37 2020 +0000

    snap: (auto) updated to 14.13.1
```

those two commits for 14.14.0 are identical, content-wise, but the timestamp is different.

I've force pushed the latest `node14` from here to launchpad and the 14.15.0's are building now: https://launchpad.net/~nodesource/+snap/node14

I've checked the other branches and they are in sync. I'm going write this one down to setup pain. But if we see this again, we might want to add a `--force` in the push to launchpad to make sure it's in sync and hopefully that isn't just papering over a more fundamental problem (there's a risk, if there's some kind of race, that we keep force pushing a re-build and it keeps on publishing new builds, so we need to make sure we get it right).
