### ISSUE TITLE
Latest v16 failed to build

### ISSUE THREAD

**Issue by rvagg** [nodejs/snap#11]
https://launchpad.net/~openjs/node-snap/+snap/node16

Launchpad container problems by the look of the logs. I've requested a rebuild and 🤞 but am heading off for the day. This issue is a reminder to follow up (someone else who has access could do so too, and if they get green builds then this issue can be closed).

**Comment by richardlau** [comment]
Everything looks green so closing. 

![image](https://user-images.githubusercontent.com/5445507/118852544-cac8e480-b8ca-11eb-8d4c-7acdc0da96df.png)
