### ISSUE TITLE
"cannot change profile for the next exec call : No such File or Directory" Error while trying to use npm in Debian Unstable

### ISSUE THREAD

**Issue by Anish-M-code** [nodejs/snap#15]
![snappy](https://user-images.githubusercontent.com/58029804/132116412-be0ad63f-077d-4254-99f8-c90a5eb66e7e.png)

snap version: 2.51.7-1
I installed node 16 using sudo snap install node --channel=16/stable --classic
I did restart the computer after installing both snap and after installing node to mitigate potential problems.

**Comment by rvagg** [comment]
Sorry, I haven't seen this before! It might be something to report to the Snap folks @ https://forum.snapcraft.io/ as I doubt this is specific to the Node.js snap, it seems like something related to the Snap containment and/or wrapping.

**Comment by Anish-M-code** [comment]
ok thanks for reply.
