### ISSUE TITLE
Node 16 is active LTS but not default from store

### ISSUE THREAD

**Issue by Larry1123** [nodejs/snap#23]
As of 2021-10-26 Node 16 became the active LTS of node, the snap [readme](https://github.com/nodejs/snap#default-release-line) ask for a reminder so here it is.

**Comment by richardlau** [comment]
Updated
![image](https://user-images.githubusercontent.com/5445507/140403441-78b7a470-7179-4133-ba16-e5b7e95dfb43.png)
