### ISSUE TITLE
16/stable is at 16.14.0 but 16.14.2 is available

### ISSUE THREAD

**Issue by jdstrand** [nodejs/snap#34]
`snap info node` shows that the 16/stable channel is at 16.14.0 but 16.14.2 is available. It looks like it is the same with 14.19.1-- 14/stable has 14.19.0 but 14.19.1 is available.

Thanks and thanks for the snap!

**Comment by rvagg** [comment]
see #30, unfortunately needs people time and attention to figure it out, something I don't have much of right now

**Comment by rvagg** [comment]
#30 got fixed, 16.15.0 is now in the store as is 14.19.1.
