### ISSUE TITLE
Update default value to v18 LTS

### ISSUE THREAD

**Issue by ruyadorno** [nodejs/snap#45]
cc @richardlau

**Comment by richardlau** [comment]
I've set 18 to be the default track. I think we missed requesting a new track for Node.js 19 but it's way too late in the evening for me to do that.

**Comment by rvagg** [comment]
Have requested a 19: https://forum.snapcraft.io/t/track-request-for-node-19/32364

**Comment by rvagg** [comment]
We've been given 19, someone just needs to wire it up. I could probably do it tomorrow unless someone gets to it first.

**Comment by rvagg** [comment]
```
  19/stable:        19.0.0                         2022-10-27 (6864) 33MB classic
  19/candidate:     ↑
  19/beta:          ↑
  19/edge:          ↑
```

19 has been set up and is running now in cron; I added additional IBM architectures while I was in there for 16 and 18 as well as the new 19
