### ISSUE TITLE
node snap based on ubuntu22

### ISSUE THREAD

**Issue by ZmRZjFuDsDiR4qi5801F** [nodejs/snap#49]
Hello,

currently the node snap is based on core20 but we need to upgrade our devices to ubuntu22, so would it be possible to upgrade the snapcraft.yaml of the snap to base: core22 ? Do you have any plans regarding or is a time schedule available?
Thank you in advance.

**Comment by rvagg** [comment]
No schedule, switching to core22 for the next major release might be a good idea. Upgrading your devices to ubuntu22 should be fine while still using these snaps, that's part of the point, they come with the core20 components so are not too dependent on the OS you're running.

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
The reason for core22 is our ctrlX Node.js API, based on NAPI using our C++ native API compiled against core22, so we need a newer version of g++ (gcc) libs contained in the node snap execution environment, else we get an runtime error because of an older versions found by ld. So it would be nice to have core22 for node next major. As an workaround we can use the *.tar based installation for development, but this is not an option for our target ctrlX Core devices, based on uc22 core (snappy).

**Comment by rvagg** [comment]
yeah, that's fair enough I think.

and .. it looks like I've (and others) neglected to get a `20` out so maybe it could be done now

care to PR against `main` to put `core22` in snapcraft.yml.sh to get the ball rolling?

**Comment by rvagg** [comment]
see https://github.com/nodejs/snap/issues/50, both `latest/edge` and `20` tracks are now running `core22` and appear to be working; report back how this goes for you, I'd be interested to hear

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
I successfully tested it on our core 22 devices. This small change will reduce effort for our customers a lot, so thank you for your fast approach and support.
