### ISSUE TITLE
Snap for v21

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/snap#58]
Copying and pasting the checklist from the README:

 * [ ] 1. Request a new Track for the "node" Snap in the Snapcraft forum in the ["Store requests" section](https://forum.snapcraft.io/c/store-requests). The track should be the major release line number (e.g. `14`). The "node" Snap has fast-track approval and is usually authorized within 24 hours by the administrators. This step needs to be performed in order to upload to a new track. An example of this for `14` can be seen here: https://forum.snapcraft.io/t/track-request-for-node-14-fast-track-please/16842/3
 * [ ] 2. Create a new branch in this repository, named `nodeXX` where `XX` is the release line number.
 * [ ] 3. Edit [snapcraft.yaml.sh](./snapcraft.yaml.sh) _if_ required for system configuration required to build the new version. In most cases this is not necessary and the `master` version can be copied. Where the compiler minimums change, the equivilant changes may need to be made in the script.
 * [ ] 4. Edit [.github/workflows/cron.yml](./.github/workflows/cron.yml) to add the new release line to the matrix.
 * [ ] 5. Start a build (manually, or wait for the GitHub Action to trigger by cron), which will update the snapcraft.yaml file for that branch correctly _and_ push the new branch to https://code.launchpad.net/node-snap where it can be further configured.
 * [ ] 6. Navigate to https://code.launchpad.net/node-snap and into the new branch and click on "Create snap package".
 * [ ] 7. Manually request new builds for the Snap from the Snap configuration page in Launchpad ("Request builds").

**Comment by rvagg** [comment]
Someone else want to try running some or all of this process? Might be good to iron out whether credentials and permissions are shared in the appropriate way with Build.
