### ISSUE TITLE
No `20/stable` snap for `ppc64le`

### ISSUE THREAD

**Issue by simondeziel** [nodejs/snap#59]
We've been using `18/stable` previously and it provided most of the arches we needed (thanks!) but when moving to `20/stable`, we lost `ppc64le` support causing our build to fail:

```
:: + '[' ppc64le = riscv64 ']'
:: + snap install node --channel=20/stable --classic
:: error: snap "node" is not available on 20/stable but is available to install on
::        the following tracks:
::
::        19/stable  snap install --channel=19 node
::        18/stable  snap install --channel=18 node
::        16/stable  snap install --channel=16 node
::
::        Please be mindful that different tracks may include different features.
::        Get more information with 'snap info node'.
```

Looking at https://nodejs.org/download/release/index.tab, it looks like upstream is still building for `ppc64le` so it'd be nice to have the snap for it too, please :)

**Comment by simondeziel** [comment]
I don't have access but I think this is as easy as checking the box "PowerPC64 Little-Endian (ppc64el)" on https://launchpad.net/~openjs/+snap/node20/+edit

**Comment by rvagg** [comment]
no, it wasn't I've turned it on now and requested new builds 🤞 that it shows up, I'll keep an eye out for failed build notification and come back and update here if it does

**Comment by rvagg** [comment]
Sorry, I just noticed that myself while in there setting up a node21, maybe there was an _eventual consistency_ problem after saving the snap and requesting a new build; I did it again just now and it appears to have produced it. Got one for the new node21 too if that's interesting for you and I'll also turn it on for edge.
