### ISSUE TITLE
Cypress fails to run npm postinstall

### ISSUE THREAD

**Issue by MikeMcC399** [nodejs/snap#68]
## Issue

Attempting to install the npm module [cypress](https://www.npmjs.com/package/cypress) fails at the postinstall stage using npm.

> npm info run cypress@13.13.0 postinstall node_modules/cypress node index.js --exec install
> npm info run cypress@13.13.0 postinstall { code: 1, signal: null }

This issue does not occur if Node.js is **not** installed via snap, for instance via `nvm`.

## Steps to reproduce

On Ubuntu:

```shell
mkdir cy-test
cd cy-test
git init
npm init -y
npm install cypress -D
```

Note: If Cypress has been previously fully installed, then you need to execute the following to delete the Cypress binary from its cache:

```shell
npx cypress cache clear
```
or
```shell
rm -rf ~/.cache/Cypress
```

## Environment

Ubuntu `22.04.4` LTS
Node.js `v20.14.0 8723  20/stable` installed with snap

Continues to be reproducible with
`node  20.15.1  8864  20/stable`  (bundled npm version `10.7.0`)

### Install

```shell
npm install cypress -D --ddd
```

```text
...
npm info run cypress@13.13.0 postinstall node_modules/cypress node index.js --exec install
npm info run cypress@13.13.0 postinstall { code: 1, signal: null }
npm verbose stack Error: command failed
npm verbose stack     at ChildProcess.<anonymous> (/snap/node/8723/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verbose stack     at ChildProcess.emit (node:events:519:28)
npm verbose stack     at maybeClose (node:internal/child_process:1105:16)
npm verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm verbose pkgid cypress@13.13.0
npm verbose cwd /home/mike/github/cy-e2e-default
npm verbose Linux 6.5.0-41-generic
npm verbose node v20.14.0
npm verbose npm  v10.7.0
npm error code 1
npm error path /home/mike/github/cy-e2e-default/node_modules/cypress
npm error command failed
npm error command sh -c node index.js --exec install
npm verbose exit 1
npm verbose code 1

```
### snap

```text
$ snap list node
Name  Version  Rev   Tracking   Publisher  Notes
node  20.14.0  8723  20/stable  iojs✓      classic
```

### Workaround - split postinstall phase

```shell
npm install cypress -D --ignore-scripts
npx cypress install
```

`npx cypress install` is the equivalent of `node ./node_modules/cypress/index.js --exec install`

### Workaround - install Node.js with nvm

Install Node.js on Ubuntu with nvm according to instructions on https://nodejs.org/en/download/package-manager

```shell
# installs nvm (Node Version Manager)
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

# download and install Node.js (you may need to restart the terminal)
nvm install 20

# verifies the right Node.js version is in the environment
node -v # should print `v20.15.0`

# verifies the right NPM version is in the environment
npm -v # should print `10.7.0`
```

**Comment by MikeMcC399** [comment]
I also found that running

```shell
npm install cypress --foreground-scripts
```

is successful, so it is something connected to running an npm lifecycle script in the background using node/npm from snap on Ubuntu.

**Comment by MikeMcC399** [comment]
This issue only affects npm installed via snap node. Using yarn installed via snap node works correctly.

The following sequence completes successfully:

```shell
yarn init -y
yarn add cypress -D
yarn cypress cache list
```

**Comment by MikeMcC399** [comment]
Also reproducible installing using npm with:

Ubuntu `24.04` LTS
`node (22/stable) 22.4.1 from OpenJS Foundation (iojs✓) installed`

**Comment by MikeMcC399** [comment]
@rvagg 

Will somebody be able to give some feedback on this issue? It may need a warning in the Cypress documentation, but I'd like to understand the root cause first before proposing a documentation update.

snap is one of the recommended node package managers on https://nodejs.org/en/download/package-manager/all

**Comment by rvagg** [comment]
Sorry, I don't have clear advice for you on this one, snaps have trouble doing child process execs because they are already executed in constrained environments; I opt to not use node from a snap if I want to not bump into these problems. I wish I could get to the bottom of it and be able to either provide advice or fix something, but it's not obvious to me where to start digging and I don't have the time or reason to dig deeper, sorry.

**Comment by MikeMcC399** [comment]
@rvagg 

Thanks for your valuable feedback and my apologies for pinging you!

I'm going to assume that the problem is inherent to snap and I'll propose a documentation update to Cypress. I don't personally use snap as a package manager for node (I prefer `n` & `nvm`), but some other Cypress users have hit this issue and I'm trying to make sure that other users won't fall into the same trap.

**Comment by MikeMcC399** [comment]
Now documented on 

https://docs.cypress.io/guides/getting-started/installing-cypress#npm-install

**Comment by MikeMcC399** [comment]
Closing, as it appears to be an architectural restriction with snap.

As mentioned above in https://github.com/nodejs/snap/issues/68#issuecomment-2253062008, it is now documented for Cypress, although the link has now moved to https://docs.cypress.io/app/get-started/install-cypress#npm-install.

**Comment by rvagg** [comment]
From the `26` track going forward (including `edge` track), we're pulling the binaries from nodejs.org and bundling those, so it retains the ABI floor established there, with only `libatomic.so.1` isolated inside the snap. I believe this and the configuration changes, relying on the host rather than the snap symbols and libraries should address this problem 🤞.

**Comment by MikeMcC399** [comment]
Thanks for the tip! I confirmed that you're right, however npm >=11.16.0 has introduced checks on lifecycle scripts. that are blocked in npm@12

Node.js 26.5.0 bundles npm@11.17.0 so these are only warnings at the moment, and the installation succeeds.

## Steps to reproduce

On Ubuntu 26.04 LTS

```shell
sudo snap install node --classic --channel=26
npm --version
cd $(mktemp -d)
npm install cypress --save-dev
npm approve-scripts cypress --no-allow-scripts-pin
npm rebuild cypress
npx cypress verify
```

## Logs

```console
$ sudo snap install node --classic --channel=26
npm --version
cd $(mktemp -d)
npm install cypress --save-dev
npm approve-scripts cypress --no-allow-scripts-pin
npm rebuild cypress
npx cypress verify
node (26/stable) 26.5.0 from OpenJS Foundation (iojs✓) installed
11.17.0

added 169 packages in 34s

53 packages are looking for funding
  run `npm fund` for details
npm warn allow-scripts 1 package has install scripts not yet covered by allowScripts:
npm warn allow-scripts   cypress@15.18.1 (postinstall: node dist/index.js --exec install)
npm warn allow-scripts
npm warn allow-scripts Run `npm approve-scripts --allow-scripts-pending` to review, or `npm approve-scripts <pkg>` to allow.
Approved cypress:
  added cypress
rebuilt dependencies successfully

✔  Verified Cypress! /home/mike/.cache/Cypress/15.18.1/Cypress
```

**Comment by rvagg** [comment]
yeah, but that's now an npm/cypress/you problem, not a snap problem! Thanks for the output because it confirms the approach I made here works and I'm _very_ happy about to see this because I've been wrestling with this problem for a few years and I even switched from using the snap myself for similar reasons, but I'm back on the snap now and am giving it a spin again to see if it fails me 🤞

**Comment by MikeMcC399** [comment]
> yeah, but that's now an npm/cypress/you problem, not a snap problem! 

I only mentioned this for completeness. As you say, it's not a snap issue.

> Thanks for the output because it confirms the approach I made here works and I'm _very_ happy about to see this because I've been wrestling with this problem for a few years and I even switched from using the snap myself for similar reasons, but I'm back on the snap now and am giving it a spin again to see if it fails me 🤞

Congratulations and good to see that your effort has been repaid by success! 🚀
